### ISSUE TITLE
The quality in the distance gets really weird

### ISSUE THREAD

**Issue by Quix1** [ferriarnus/acedium#11]
Well my Quality gets really bad even on 64 chuncks.
It looks so weird, like all the blocks are bordered by lines.
![image](https://github.com/ferriarnus/acedium/assets/92585313/4935602a-f54f-49a4-b0ad-eee1849a1255)
![image](https://github.com/ferriarnus/acedium/assets/92585313/d743fee1-2751-4cc4-9ebc-cf87ae3cad3e)

**Comment by mpustovoi** [comment]
It seems to me that this is inevitable with loading at such a distance. Maybe everything rests on the lack of antialiasing in Minecraft at all. This is most noticeable with transparent foliage in jungle.

**Comment by ferriarnus** [comment]
I indeed think this is just what happens at large distances, nothing special I can fix.
