### ISSUE TITLE
it wont render

### ISSUE THREAD

**Issue by Zeroblacck** [ferriarnus/acedium#12]
![image](https://github.com/ferriarnus/acedium/assets/142685526/580dd0d8-69f5-4c68-96c9-9ca889421109)
when "nvidium" is enabled, nothing render, when i disable, it renders back..
im usin 1.20.1 btw

**Comment by ferriarnus** [comment]
What other mods are you using?

**Comment by Zeroblacck** [comment]
nvm, i already fixed, sorry
