### ISSUE TITLE
Can you make a 1.18.2 Forge port of nvidium if possible.

### ISSUE THREAD

**Issue by lrj1818** [ferriarnus/acedium#14]
So i can use it in modpacks etc heavy chunks drop mah framerate

**Comment by ferriarnus** [comment]
Unfortunaty, this isn't possible. Nvidium depends on sodium 0.5.x, and that version isn't on 1.18.2. So either I would need to backport sodium, or I would need to rewrite a large part of nvidium. I do not have the time (or motivation) to take on such a large project.

**Comment by antdoesthings** [comment]
Isn't embeddium a fork of sodium 0.5.8 for 1.18.2 forge? And it's open source?

**Comment by ferriarnus** [comment]
No, embeddium is a sodium port yes, but on 1.18.2, it is not using sodium 0.5.8 as a base, but sodium 0.3.x or something iirc. So it is missing some features for it to work.

**Comment by antdoesthings** [comment]
Oh mb I thought the description "An open-source client performance mod for Minecraft (based on **Sodium 0.5.8**) prioritizing reliability & mod compatibility" applies to all of its' versions. (idk how to word this, I don't mean to come off as sarcastic or negative or anything like that)
