### ISSUE TITLE
transparacy Issue

### ISSUE THREAD

**Issue by TamsynnImogen** [ferriarnus/acedium#2]
![2024-01-01_17 50 27](https://github.com/ferriarnus/acedium/assets/11425374/87e6bff2-297e-4f45-b790-1bfa6d818574)
i have a nvidia 1660ti gpu but it seems to be messing up the textures (seemingly reversing transparency

**Comment by ferriarnus** [comment]
Ok, so there are 2 things: 1) don't use translucent sorting from embeddium, that messes with the sorting nvidium (and thus also acedium) does. 2) Don't use the latest embeddium, as they have made a change I haven't fixed (yet).

**Comment by ferriarnus** [comment]
Closing since no reply. Feel free to send if this didn't fix it.

**Comment by TamsynnImogen** [comment]
hi thanks for the tips ive gone down to embeddium 0.2.13 (november release) and that seemed to fix the issue
