### ISSUE TITLE
Problem with mixy and acedium

### ISSUE THREAD

**Issue by tablenitro** [ferriarnus/acedium#22]
i tried to use mixy with acedium and it doesent work, i downloaded the mods and put them correctly just in case theres the versions:
acedium-0.2.7-beta.jar
mixy-0.1.5-alpha.jar

nvm i fixed it

**Comment by ferriarnus** [comment]
can you send me a log?

**Comment by tablenitro** [comment]
> can you send me a log?

no need i just messed up with the file directories that i had.
