### ISSUE TITLE
The minecraft application is broken now

### ISSUE THREAD

**Issue by tablenitro** [ferriarnus/acedium#23]
Welp, after i deleted acedium to put distant horizons mod its still had acedium features even tho it was deleted, idk what to do i reinstalled and even deleted files from %appdata%/minecraft and curseforge so new data can rewrite that, but... It didnt fix it, idk what to do.  Please help me.
Note: If someone reads it dont expect me to respond right away, ill probably respond tomorrow

**Comment by ferriarnus** [comment]
That sounds like you didn't delete it from the right folder. On the curseforge profile, left click to open more options and clilck open folder.

**Comment by tablenitro** [comment]
> That sounds like you didn't delete it from the right folder. On the curseforge profile, left click to open more options and clilck open folder.

i made sure i deleted things from specificly curseforge mod folder, even if it was the case i deleted the appdata surely after, so new data can rewrite its self and yet i still have the same problem.

**Comment by ferriarnus** [comment]
If the mod is truely deleted, it won't show up in game. Have a look in the latest log, it should both show the mod folder location as the installed.
