### ISSUE TITLE
[Bug] Physics objects are invisible from Valkeryian Skies

### ISSUE THREAD

**Issue by FemBane** [ferriarnus/acedium#25]
Honestly, not sure what's possible to fix with it. The entities are just gone for me, provided, I do have 390~ mods, It's just VS that has the issue, disabling Nvidium in-game allows the ships to appear.
Logs don't show errors unfortunately
latest.log: https://mclo.gs/Z5jDhe7
debug.log: https://mclo.gs/dRil0rL

**Comment by ferriarnus** [comment]
known issue in nvidium. I don't think this will be fixed soon

**Comment by FemBane** [comment]
RIP, frame boost with Nvidium is substantial, too... Some things are just too good to be true x3
