### ISSUE TITLE
[1.20.1] Can't get Acedium to work

### ISSUE THREAD

**Issue by slendercreeper1010** [ferriarnus/acedium#27]
I have installed
embeddium
embeddium++
Acedium
Invidiun (+ Connector)

(+ other optimization mods, like InstantlyFast, MemoryLeak, Boccium,)

Then I launch and log into the world I see no effect. Mod is present in "Mod" menu, but doesn't show up in Embeddium video settings tab

![image](https://github.com/user-attachments/assets/5863aefc-a7d7-44d8-baf6-4a71fadb17db)
![image](https://github.com/user-attachments/assets/8a281ff5-5caa-4aff-aca3-555147063856)

**Comment by ferriarnus** [comment]
do you have a nvidia gpu higher then or equal to the 16xx series?

**Comment by slendercreeper1010** [comment]
> do you have a nvidia gpu higher then or equal to the 16xx series?

I have Nvidia GTX 1660 Ti (Laptop)

**Comment by ferriarnus** [comment]
Is this gpu being used by minecraft, what does it say when you look in the f3 menu? Otherwise you may need to look up how to make your Nvidia gpu being used by java.

**Comment by slendercreeper1010** [comment]
> Is this gpu being used by minecraft, what does it say when you look in the f3 menu? Otherwise you may need to look up how to make your Nvidia gpu being used by java.

I WAS an integrated GPU instead of GTX. Now everything works like a charm. Thank you for your awesome mod
