### ISSUE TITLE
Upload to curseforge so we can use in modpacks?

### ISSUE THREAD

**Issue by Jetpack-Cat** [ferriarnus/acedium#28]
Hey we can't use this mod in modpacks if it's not uploaded to curseforge, is there a reason you haven't?

Thanks

**Comment by ferriarnus** [comment]
As stated in the Readme, no I don't plan to. There are a couple of reasons, ranging from not being sure on how well I can maintain, to the "issue" of ownership, as I will not upload it without some understanding with cortex (which, as per reason 1, I am currently not asking about).
