### ISSUE TITLE
I have a question with a 1.20.1 based forge version.

### ISSUE THREAD

**Issue by tangzixiang-hash** [ferriarnus/acedium#3]
My graphics card is 4070ti
When I was playing atm9, I found your mod on the web, I found it very useful, and I added it, but I found that it didn't work, but I could see the corresponding menus and options in the video menu.
Then I tick Disable, or Enable Nvidium, and I observe that there is no detailed change in the number of frames, please ask, what report can I provide to report this problem.

**Comment by ferriarnus** [comment]
I think the disable button in the option menu might be broken in the last release. Iirc, it mainly exists to indicate that iris has disabled the mod. If you go to tye f3 screen, it should say it's using nvidium. To test with and without it seems you will need to remove the mod fully at this point.

**Comment by liangmoe** [comment]
tested a few terrain 32 distances render for in game toggle on and toggle off comparison, it did work, cool

![2024-01-11_15 27 03](https://github.com/ferriarnus/acedium/assets/135343248/61e27b45-56f7-4264-9295-ace1a25008f7)
![2024-01-11_15 28 09](https://github.com/ferriarnus/acedium/assets/135343248/2c8d0d73-9914-4364-9ff4-912b06c76cda)
![2024-01-11_15 29 17](https://github.com/ferriarnus/acedium/assets/135343248/137c098f-0dd9-48d0-9e67-4cb46b227ccc)

![2024-01-11_15 30 02](https://github.com/ferriarnus/acedium/assets/135343248/96a5874e-1003-40cd-af88-904b5a06aa68)

**Comment by tangzixiang-hash** [comment]
I don't think my graphics card is working
![image](https://github.com/ferriarnus/acedium/assets/60438085/f674f39b-57b8-476c-8648-b82a73f291b7)

**Comment by tangzixiang-hash** [comment]
![image](https://github.com/ferriarnus/acedium/assets/60438085/939cb0a8-36db-4b23-a807-792d3a866149)

**Comment by ferriarnus** [comment]
It does seem to work from that screenshot? At least it's acting as if it's working. What fps do you get? Is vsync off and frames put to unlimited?

**Comment by tangzixiang-hash** [comment]
I chose chunk 255 to load and then he didn't load.

**Comment by liangmoe** [comment]
i assume you are using bobby reforged, but without acedium your issue will still occured, should be the issue from bobby reforged's side; if you use the original fabric bobby with connector and encountered the same issue then the issue must be connector side as bobby work as intended on fabric side

the screenshot is taken by using bobby reforge with acedium

![2024-01-13_21 23 18](https://github.com/ferriarnus/acedium/assets/135343248/d7504eb1-7dd1-4cb0-be37-6a53572294b1)

**Comment by tangzixiang-hash** [comment]
![image](https://github.com/ferriarnus/acedium/assets/60438085/e114830f-bcb0-40b9-be3e-340349be9c7b)

I only added this mod, I didn't add this Bobby Reforge, is it a must

**Comment by liangmoe** [comment]
idk then, surely Bobby Reforge is not a must, just a way i have been successfully caching chunk and reach much render distance if i want, if your issue still occured without any mod then might be a forge thing🙁

**Comment by ferriarnus** [comment]
I think you misunderstood what that setting does. The setting you are talking about is basically "remembering" chunks that have been loaded. You will first need to load these 255 chunks before you can see them, as they will not load automatically.
