### ISSUE TITLE
Acedium doesnt work with Sodium 1.21.1

### ISSUE THREAD

**Issue by ScoutTheSaneless** [ferriarnus/acedium#35]
I wanted to try and run this mod with my 1.21.1 pack alongside shaders, which needs Iris, which needs Sodium. But Acedium decided it needed Embeddium for some odd reason and didnt like having Sodium. Is this intended or not?

**Comment by OracleHisty** [comment]
1.21.1 has an Official NeoForge port of Sodium. If you need have issues on 1.21.1, refer to Sodium/Embeddium liscense changes as of recently.

**Comment by OracleHisty** [comment]
Updating to Neoforge would take a lot of extra work to clear all of the incompatibilities due to the hard split in liscensing.

**Comment by ferriarnus** [comment]
So in short, in 1.21, sodium and embeddium use different api's. This means you can not use sodium without rewriting some stuff. Besides that, I think sodium compat is something for the upstream project, nvidium, as it feels a bit weird to do that here. Cortex will probably look into it after sodium is no longer a beta, so don't try to rush her.
