### ISSUE TITLE
Forge

### ISSUE THREAD

**Issue by Kreatifchk** [ferriarnus/acedium#4]
why is it like this on Forge?

![acc](https://github.com/ferriarnus/acedium/assets/24816032/d5eb5192-a91a-40ae-9df6-88146c6b0a81)

**Comment by ferriarnus** [comment]
I forgot to remove the fabric.json file. However that error should not show up on neoforge if you use the right mc version. (I will however update the releases later to fix it).

**Comment by TSEG6** [comment]
this is an issue again with the newest version, both on forge and neoforge

edit: I am running it on 1.20.1 which I believe should still be supported
edit2: I should've looked more, this doesn't support 1.20.1 yet, sorry!

**Comment by ferriarnus** [comment]
So this should only happen if you use the wrong version. As such I will close this issue.
