### ISSUE TITLE
will there be a port on 1.19.2?

### ISSUE THREAD

**Issue by Suilte** [ferriarnus/acedium#5]
I would like to see the mod ported to 1.19.2

**Comment by ferriarnus** [comment]
I'm unsure if embeddium has the needed sodium version for it (as that is what stopped nvidium from updating).

**Comment by InsaanNotFound** [comment]
Bump, also would love it.

**Comment by eristocrates** [comment]
> I'm unsure if embeddium has the needed sodium version for it (as that is what stopped nvidium from updating).

Has there been any progress in finding out? ngl If i knew what the needed sodium version was I'd try to find out myself.

**Comment by ferriarnus** [comment]
Unfortunaty, this isn't possible. Nvidium depends on sodium 0.5.x, and that version isn't on 1.19.2. So either I would need to backport sodium, or I would need to rewrite a large part of nvidium. I do not have the time (or motivation) to take on such a large project.

**Comment by martinhuynh** [comment]
What about Embeddium?
