### ISSUE TITLE
Everything invisible exept particles when activated

### ISSUE THREAD

**Issue by SpeedySnaky** [ferriarnus/acedium#7]
I tried this mod and every block/entity is invisible when I activate Acedium. Is there a way to fix this? 
Ver: 1.20.1, Forge

**Comment by UltimatChamp** [comment]
You are probably using it with Embeddium 0.3.1. Try using it with Embeddium 0.2.18/19!

**Comment by UltimatChamp** [comment]
Also, if this is the case, duplicate of #6!
