### ISSUE TITLE
Does the lone 1.20.4 release work on 1.20.1?

### ISSUE THREAD

**Issue by Acheron-Sunset** [ferriarnus/acedium#9]
I'm sorry for the frankly uneducated question, but I had to ask.

If I took this port, and installed it on my 1.20.1 install, would it work? My first guess is no, but I figured it wouldn't hurt to try asking anyways.

thank you for your time.

**Comment by ferriarnus** [comment]
Their is 1.20.1 version as well https://github.com/ferriarnus/acedium/releases/tag/v0.2.6-1.20.1
